# -*- coding: utf-8 -*-
"""
Test how effective SNAPS is at assigning with simulated predicted shifts, 
generated by adding Gaussian noise to the real shifts

@author: Alex
"""

import numpy as np
import pandas as pd
# from SNAPS_importer import SNAPS_importer
# from SNAPS_assigner import SNAPS_assigner
from SNAPS_analyse import import_testset_metadata, check_assignment_accuracy, collect_assignment_results, summarise_results
from pathlib import Path
import argparse
from subprocess import run
from plotnine import *

parser = argparse.ArgumentParser(
        description="Test SNAPS on simulated predicted shifts")
parser.add_argument("SNAPS_path", help="Path to the top-level SNAPS directory.")
parser.add_argument("-p", "--python_cmd", default="python")
parser.add_argument("--assign", action="store_true", help="Do SNAPS assignment for simulated predictions.")
parser.add_argument("--analyse", action="store_true", help="Analyse results for simulated predictions.")
parser.add_argument("-N", default=None, help="Limit to first N datasets.")
args = parser.parse_args()

# path = Path("C:/Users/alexh/GitHub/SNAPS/")
path = Path(args.SNAPS_path)

testset_df = import_testset_metadata(path)

id_all_carbons = [
        'A002', 'A003', 'A004', 'A005', 'A006', 'A008', 'A009', 'A010', 'A011',
        'A012', 'A013', 'A014', 'A015', 'A016', 'A017', 'A018', 'A019', 'A020',
        'A021', 'A023', 'A025', 'A026', 'A027', 'A028', 'A029', 'A033', 'A035',
        'A036', 'A037', 'A039', 'A043', 'A044', 'A045', 'A049', 'A050', 'A051',
        'A053', 'A059', 'A061', 'A062', 'A066', 'A067', 'A069']

# Limit how many datasets are assigned/analysed
if args.N is not None:
    id_all_carbons = id_all_carbons[0:int(args.N)]

def make_cmd(id, out_dir, config_file="config.txt", extra_args=[]):
    """Extra_args is a list of additional command line arguments"""
    print(out_dir, ":", id)
    cmd = [args.python_cmd, (path/"python/SNAPS.py").as_posix(),
            testset_df.loc[id, "obs_file"].as_posix(),
            testset_df.loc[id, "preds_file"].as_posix(),
            (path/"output"/out_dir/(testset_df.loc[id, "out_name"]+".txt")).as_posix(),
            "--shift_type", "test",
            "--pred_type", "shiftx2",
            "-c", (path/"config"/config_file).as_posix(),
            "-l", (path/"output"/out_dir/(testset_df.loc[id, "out_name"]+".log")).as_posix()]
    cmd = cmd + extra_args

    return(cmd)

# Simulate predicted shifts with all atoms except HA
error_multipliers = [0, 0.025, 0.05, 0.075, 0.1, 0.15, 0.2, 0.25]

if False:   #   args.assign:
    for error_multiplier in error_multipliers:
        out_dir = "sim_preds_carbons_"+str(error_multiplier)
        # Create output directory, if it doesn't already exist
        (path/"output"/out_dir).mkdir(parents=True, exist_ok=True)
        for id in id_all_carbons:
            seed = testset_df.loc[id, "BMRB"].astype(str)   # Use the BMRB ID if the observed shifts as the random seed   
            cmd = make_cmd(id, out_dir, config_file="test/config_sim_preds.yaml", 
                            extra_args=["--simulate_pred_shifts", 
                                        "--sim_pred_multiplier", str(error_multiplier), 
                                        "--sim_pred_seed", seed])
            run(cmd)

if args.analyse:
    assigns = {}
    summary = {}
    for error_multiplier in error_multipliers:
        out_dir = "sim_preds_carbons_"+str(error_multiplier)
        assigns[error_multiplier] = collect_assignment_results(path/"output"/out_dir, testset_df, ID_list=id_all_carbons)
        summary[error_multiplier] = summarise_results(assigns[error_multiplier])
    
    # Plot overall assignment accuracy vs error
    overall_accuracy = pd.DataFrame({"Error":error_multipliers, 
                                     "Pc_correct":[summary[x].loc[0, "Pc_correct"] for x in error_multipliers]})
    plt = ggplot(overall_accuracy) + geom_point(aes(x="100*Error", y="Pc_correct"))
    plt = plt + geom_title("Overall assignment accuracy as a function of simulated prediction error (all carbons)")
    plt = plt + ylab("Accuracy (%)") + xlab("Error (% of 95% interval)")
    plt = plt + scale_y_continuous(breaks=np.arange(0,101,10), limits=(0,100)) 
    plt += theme_bw()
    plt.save(path/"plots/sim preds accuracy carbons.pdf", height=100, width=100, units="mm")

    # Plot assignment accuracy against protein size, faceted by error
    summary_all = None
    for x in error_multipliers:
        summary[x]["Error_multiplier"] = x
        if summary_all is None:
            summary_all = summary[x]
        else:
            summary_all = pd.concat([summary_all, summary[x]])
    summary_all = summary_all[summary_all.ID!="Sum"]
    
    plt = ggplot(summary_all) + geom_point(aes(x="N.astype(int)", y="Pc_correct.astype(float)"))
    plt = plt + facet_wrap("Error_multiplier")
    plt = plt + geom_title("Assignment accuracy vs protein size,at different simulated error levels (all carbons)")
    plt = plt + ylab("Accuracy (%)") + xlab("Number of residues")
    plt = plt + scale_y_continuous(breaks=np.arange(0,101,10), limits=(0,100)) 
    plt += theme_bw()
    plt.save(path/"plots/sim preds accuracy carbons - size.pdf", height=200, width=200, units="mm")

# Simulate predicted shifts with only H and N
error_multipliers = [0, 0.005, 0.01, 0.015, 0.02, 0.025,0.05,0.075,0.1,0.15, 0.2, 0.25]

if args.assign:
    for error_multiplier in error_multipliers:
        out_dir = "sim_preds_HN_"+str(error_multiplier)
        # Create output directory, if it doesn't already exist
        (path/"output"/out_dir).mkdir(parents=True, exist_ok=True)
        for id in id_all_carbons:
            seed = testset_df.loc[id, "BMRB"].astype(str)   # Use the BMRB ID if the observed shifts as the random seed   
            cmd = make_cmd(id, out_dir, config_file="test/config_sim_preds_HN.yaml", 
                            extra_args=["--simulate_pred_shifts", 
                                        "--sim_pred_multiplier", str(error_multiplier), 
                                        "--sim_pred_seed", seed])
            run(cmd)

if args.analyse:
    assigns = {}
    summary = {}
    for error_multiplier in error_multipliers:
        out_dir = "sim_preds_HN_"+str(error_multiplier)
        assigns[error_multiplier] = collect_assignment_results(path/"output"/out_dir, testset_df, ID_list=id_all_carbons)
        summary[error_multiplier] = summarise_results(assigns[error_multiplier])
    
    # Plot overall assignment accuracy vs error
    overall_accuracy = pd.DataFrame({"Error":error_multipliers, 
                                     "Pc_correct":[summary[x].loc[0, "Pc_correct"] for x in error_multipliers]})
    plt = ggplot(overall_accuracy) + geom_point(aes(x="100*Error", y="Pc_correct"))
    plt = plt + geom_title("Overall assignment accuracy as a function of simulated prediction error (amide HN only)")
    plt = plt + ylab("Accuracy (%)") + xlab("Error (% of 95% interval)")
    plt = plt + scale_y_continuous(breaks=np.arange(0,101,10), limits=(0,100)) 
    plt += theme_bw()
    plt.save(path/"plots/sim preds accuracy HN.pdf", height=100, width=100, units="mm")

    # Plot assignment accuracy against protein size, faceted by error
    summary_all = None
    for x in error_multipliers:
        summary[x]["Error_multiplier"] = x
        if summary_all is None:
            summary_all = summary[x]
        else:
            summary_all = pd.concat([summary_all, summary[x]])
    summary_all = summary_all[summary_all.ID!="Sum"]
    
    plt = ggplot(summary_all) + geom_point(aes(x="N.astype(int)", y="Pc_correct.astype(float)"))
    plt = plt + facet_wrap("Error_multiplier")
    plt = plt + geom_title("Assignment accuracy vs protein size,at different simulated error levels (amide HN only)")
    plt = plt + ylab("Accuracy (%)") + xlab("Number of residues")
    plt = plt + scale_y_continuous(breaks=np.arange(0,101,10), limits=(0,100)) 
    plt += theme_bw()
    plt.save(path/"plots/sim preds accuracy HN - size.pdf", height=200, width=200, units="mm")

#%%
if False: 
    a = SNAPS_assigner()

    a.read_config_file(path/"config/config.txt")


    # Import observed and (simulated) predicted shifts
    importer = SNAPS_importer()
    importer.import_testset_shifts(path/"data/testset/simplified_BMRB/6338.txt")
        
    a.obs = importer.obs

    a.import_pred_shifts(path/"data/testset/shiftx2_results/A002_1XMTA.cs", "shiftx2")

    sim_pred_sd = {"H":0.1711, "N":1.1169, "HA":0.1231, "C":0.5330, "CA":0.4412, "CB":0.5163}
    #{"C":1,"CA":1,"CB":1,"H":10,"N":10,"HA":10}


    sim_preds = a.simulate_pred_shifts(path/"data/testset/simplified_BMRB/6338.txt", 
                                    sim_pred_sd, seed=1)

    #%% Try doing the assignment
    a.add_dummy_rows()
    a.calc_log_prob_matrix2(sf=1, verbose=False)
    matching = a.find_best_assignments()
    a.make_assign_df(matching, set_assign_df=True)
    assign_df = a.check_assignment_consistency(threshold=0.1)

    sum((assign_df["Res_name"]==assign_df["SS_name"]))

    #%% Do this for all datasets

    (path/"output/sim_predictions/0").mkdir(parents=True, exist_ok=True)

    def test_simulated_preds(output_dir, id_list, sim_pred_sd, seed=None, atom_set=None):
        # Create output directory if it doesn't already exist
        Path(output_dir).mkdir(parents=True, exist_ok=True)
        
        for id in id_list:
            print(id)
            # Import observed and (simulated) predicted shifts
            importer = SNAPS_importer()
            importer.import_testset_shifts(testset_df.loc[id, "obs_file"])
            
            a = SNAPS_assigner()
            a.read_config_file(path/"config/config.txt")   
            
            if atom_set is not None:
                a.pars["atom_set"] = atom_set
            
            a.obs = importer.obs
            a.simulate_pred_shifts(testset_df.loc[id, "obs_file"], 
                                            sim_pred_sd, seed=seed)
            
            a.add_dummy_rows()
            a.calc_log_prob_matrix2(sf=1, verbose=False)
            matching = a.find_best_assignments()
            a.make_assign_df(matching, set_assign_df=True)
            a.check_assignment_consistency(threshold=0.1)
            a.assign_df.to_csv(Path(output_dir)/(testset_df.loc[id, "out_name"]+".txt"), 
                            sep="\t", float_format="%.3f", index=False)
            
        assigns, summary = check_assignment_accuracy(output_dir, testset_df, id_list)
        return(assigns, summary)

    def import_testset_shifts(filename, remove_Pro=True, 
                            short_aa_names=True, SS_class=None, SS_class_m1=None):
        """ Import observed chemical shifts from testset data
        
        This function is intended for use with test data only, and is unlikely 
        to work well on 'real' data.
        
        filename: The simplified BMRB file containing observed shift info.
        remove_Pro: If True, remove proline residues from output
        short_aa_names: If True, single letter aa codes are used, otherwise 3 
            letter codes are used
        SS_class: Either None or a list of strings, each of which is a list of 
            amino acids (eg. ["VIA","G","S","T","DN","FHYWC","REKPQML"] would 
            give the HADAMAC classes). If not None, a column SS_class will be 
            created which gives the class containing the residue type.
        SS_class_m1: as above, but for the i-1 residue.
        
        """
        #### Import the observed chemical shifts
        obs_long = pd.read_table(filename)
        obs_long = obs_long[["Residue_PDB_seq_code","Residue_label",
                                "Atom_name","Chem_shift_value"]]
        obs_long.columns = ["Res_N","Res_type","Atom_type","Shift"]
        # Convert residue type to single-letter code
        if short_aa_names: 
            obs_long["Res_type"] = obs_long["Res_type"].apply(seq1)
            obs_long["SS_name"] = (obs_long["Res_N"].astype(str) + 
                    obs_long["Res_type"])
            obs_long["SS_name"] = obs_long["SS_name"].str.rjust(5)
        else:
            obs_long["SS_name"] = (obs_long["Res_N"].astype(str) + 
                                    obs_long["Res_type"])
            obs_long["SS_name"] = obs_long["SS_name"].str.rjust(7)
            obs_long["Res_type"] = obs_long["Res_type"].apply(seq1)
        obs_long = obs_long.reindex(columns=["Res_N","Res_type","SS_name",
                                                "Atom_type","Shift"])
        
        # Convert from long to wide
        obs = obs_long.pivot(index="Res_N", columns="Atom_type", 
                                values="Shift")
        
        # Add the other columns back in
        tmp = obs_long[["Res_N","Res_type","SS_name"]]
        tmp = tmp.drop_duplicates(subset="SS_name")
        tmp.index = tmp["Res_N"]
        obs = pd.concat([tmp, obs], axis=1)
        
        # Make columns for the i-1 observed shifts of C, CA and CB
        obs_m1 = obs[list({"C","CA","CB","Res_type"}.intersection(obs.columns))]
        obs_m1.index = obs_m1.index+1
        obs_m1.columns = obs_m1.columns + "_m1"
        obs = pd.merge(obs, obs_m1, how="left", left_index=True, 
                        right_index=True)
        
        # Restrict to specific atom types
        atom_set = {"H","N","C","CA","CB","C_m1","CA_m1","CB_m1","HA"}
        obs = obs[["Res_N","Res_type","Res_type_m1","SS_name"]+
                    list(atom_set.intersection(obs.columns))]
        
        # Add SS_class information
        if SS_class is not None:
            obs["SS_class"]=obs["Res_type"]
            for g in SS_class:
                obs["SS_class"] = obs["SS_class"].str.replace("["+g+"]", g)
        if SS_class_m1 is not None:
            obs["SS_class_m1"]=obs["Res_type_m1"]
            for g in SS_class_m1:
                obs["SS_class_m1"] = obs["SS_class_m1"].str.replace("["+g+"]", g)
        
        obs.index = obs["SS_name"]
        obs.index.name = None
        
        if remove_Pro:
            # Remove prolines, as they wouldn't be observed in a real spectrum
            obs = obs.drop(obs.index[obs["Res_type"].isin(["PRO","P"])]) 
        
        return(obs)

    def test_simulated_preds_2(output_dir, id_list, sim_pred_sd, seed=None, atom_set=None):
        # Create some simulated predictions based on the observed residues, then assign
        Path(output_dir).mkdir(parents=True, exist_ok=True)

        for id in id_list:
            print(id)


    sd0 = {"H":0, "N":0, "HA":0, "C":0, "CA":0, "CB":0}
    assigns0, summary0 = test_simulated_preds(path/"output/sim_preds/no_error", id_all_carbons, sd0)
    assigns0.to_csv(path/("output/sim_preds/assigns0.txt"), 
                sep="\t", float_format="%.3f",index=False)
    summary0.to_csv(path/("output/sim_preds/summary0.txt"), 
                sep="\t", float_format="%.3f",index=False)


    sd_shiftx2 = pd.Series({"H":0.454, "N":2.43, "HA":0.227, "C":1.030, "CA":0.932, "CB":1.025})
    assigns_shiftx2, summary_shiftx2 = test_simulated_preds(path/"output/sim_preds/shiftx2", id_all_carbons, sd_shiftx2, seed=1)
    assigns_shiftx2.to_csv(path/("output/sim_preds/assigns_shiftx2.txt"), 
                sep="\t", float_format="%.3f",index=False)
    summary_shiftx2.to_csv(path/("output/sim_preds/summary_shiftx2.txt"), 
                sep="\t", float_format="%.3f",index=False)
    # Define the central 95% chemical shift range for each atom type 
    # (as measured in error_dist_test.py). CB set the same as CA
    qr95 = pd.Series({"C":8.24025,"CA":21.08500,"CB":21.08500,
                    "H":2.73000,"HA":2.14075,"N":23.14675})

    #%% Check with all atom types except HA
    summary_dict = {}
    assigns_dict = {}
    for x in [0,0.025,0.05,0.075,0.1,0.125,0.15,0.2,0.25]:
        print("****", str(x), "****")
        assigns, summary = test_simulated_preds(path/("output/sim_preds/qr95_"+str(100*x)), 
                                                id_all_carbons, qr95*x, seed=int(x*100),
                                                atom_set = {"H","N","C","CA","CB",
                                                            "C_m1","CA_m1","CB_m1"})
        
        assigns_dict[x] = assigns
        summary_dict[x] = summary
        
        assigns.to_csv(path/("output/sim_preds/assigns_qr95_"+str(100*x)+".txt"), 
                    sep="\t", float_format="%.3f",index=False)
        summary.to_csv(path/("output/sim_preds/summary_qr95_"+str(100*x)+".txt"), 
                    sep="\t", float_format="%.3f",index=False)
        
    keys = list(summary_dict.keys())
    tmp = pd.DataFrame({"Error":keys, "Pc_correct":[summary_dict[k].loc[0, "Pc_correct"] for k in keys]})

    #### Make a poster figure
    from plotnine import *
    plt = ggplot(data=tmp) + geom_point(aes(x="100*Error", y="100*Pc_correct"))
    plt = plt + ylab("Accuracy (%)") + xlab("Error (% of 95% interval)")
    plt = plt + scale_y_continuous(breaks=np.arange(0,101,10), limits=(0,100)) 
    plt += theme_bw()
    plt.save(path/"plots/Poster sim preds accuracy.pdf", height=100, width=100, units="mm")
    #plt = ggplot(data=assigns_shiftx2) 
    #plt = plt + geom_bar(aes(x="ID", fill="Status"), 
    #                     position=position_fill(reverse=True))
    #plt = plt + geom_text(aes(x="summary.index", label="Pc_correct"), y=0.1, 
    #                      format_string="{:.0%}", data=summary_shiftx2, angle=90)
    #plt = plt + theme(axis_text_x=element_text(rotation=90, hjust=0.5))
    #plt

    #%% Repeat, but restricting to HN only
    HN_summary_dict = {}
    HN_assigns_dict = {}
    for x in [0.2, 0.25]:#[0, 0.005, 0.01, 0.015, 0.02, 0.025,0.05,0.075,0.1,0.15]:
        print("****", str(x), "****")
        assigns, summary = test_simulated_preds(path/("output/sim_preds/qr95_"+str(100*x)), 
                                                id_all_carbons, qr95*x, seed=int(x*100),
                                                atom_set = {"H","N"})
        
        HN_assigns_dict[x] = assigns
        HN_summary_dict[x] = summary
        
        assigns.to_csv(path/("output/sim_preds/HN_assigns_qr95_"+str(100*x)+".txt"), 
                    sep="\t", float_format="%.3f",index=False)
        summary.to_csv(path/("output/sim_preds/HN_summary_qr95_"+str(100*x)+".txt"), 
                    sep="\t", float_format="%.3f",index=False)
        
    keys = list(HN_summary_dict.keys())
    tmp = pd.DataFrame({"Error":keys, "Pc_correct":[HN_summary_dict[k].loc[0, "Pc_correct"] for k in keys]})

    plt = ggplot(data=tmp) + geom_point(aes(x="100*Error", y="100*Pc_correct"))
    plt = plt + ylab("Accuracy (%)") + xlab("Error (% of 95% interval)")
    plt += scale_y_continuous(breaks=np.arange(0,101,10), limits=(0,100)) 
    #plt += scale_x_continuous(breaks=np.arange(0,16,2))
    plt += theme_bw()
    plt.save(path/"plots/Poster sim preds accuracy HN.pdf", height=100, width=100, units="mm")
